urls.py
from django.conf.urls import url
from blog import views
from django.urls import path

app_name='blog'

urlpatterns=[
    path('list',views.list,name='list'),
    path('view/<int:data>',views.vew,name='view'),
    path('writting',views.writting,name='writting')
]

forms.py
from django import forms

class blog_form(forms.Form):
    title=forms.CharField(label='Title',max_length=20,widget= forms.TextInput(attrs={'class':'form-control'}))
    data=forms.CharField(max_length=200,widget= forms.Textarea(attrs={'class':'editable'}))
    author=forms.CharField(label='author',max_length=10,widget= forms.TextInput(attrs={'class':'form-control'}))

views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from blog import forms
import mysql.connector

def db_init():
    mydb = mysql.connector.connect(
        host="localhost",
        user="djangouser",
        password="password",
        database="blog_data",
        auth_plugin='mysql_native_password'
    )

    cur = mydb.cursor()
    return cur,mydb

def database_insert(t):
    cur,mydb=db_init()

    query = "insert into data (title,author,data_d) values(%s,%s,%s)"


    cur.execute(query, t)
    mydb.commit()
    mydb.close()



def database_list():
    cur,mydb=db_init()
    query = "Select * from data"


    cur.execute(query)
    data=cur.fetchall()
    mydb.commit()
    mydb.close()
    return data

def database_list():
    cur, mydb = db_init()
    query = "Select title,author,id from data"


    cur.execute(query)
    data=cur.fetchall()
    mydb.commit()
    mydb.close()
    return data

def database_vew(key):
    cur, mydb = db_init()

    query = "Select data_d,title,author from data where id=%s"



    cur.execute(query,(key,))
    data = cur.fetchall()
    print(data)
    mydb.commit()
    mydb.close()
    return data
def index(request):
    return render(request,'blog/index.html')
def list(request):

    try:
        data=database_list()
        print(data)
        data_dic={"data":data}

    except Exception as e:
        print(e)


    return render(request,'blog/list.html',context=data_dic)


def vew(request,data):
    blog=database_vew(data)
    dict_data={"data":blog[0][0],"title":blog[0][1],"author":blog[0][2]}

    return render(request, 'blog/view.html',context=dict_data)


def writting(request):
    if request.method=='POST':
        form=forms.blog_form(request.POST)
        if form.is_valid():
            t = (form.cleaned_data['title'], form.cleaned_data['author'], form.cleaned_data['data'])
            try:

                database_insert(t)
            except Exception as e :
                print(e)




            return redirect('index')

    form=forms.blog_form()

    return render(request, 'blog/writting.html',{'form':form} )

# Create your views here.

templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Index</title>

 
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
 <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@1,300&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Lora&family=Merriweather:wght@300&display=swap" rel="stylesheet">
<style>

    .nav-item
    {
    padding-left: 20px;
    font-size: 25px;
    }
    .navbar-link
    {
    color: black;
    text-decoration: none;
    }

</style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="'container-fluid">

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
        <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="navbar-brand">Blog</li>
            <li class="nav-item"><a class="navbar-link" href="{% url 'blog:writting'%}">writting</a></li>
            <li class="nav-item"><a class="navbar-link" href="{% url 'blog:list'%}">list</a></li>

        </ul>
            </div>
    </div>
</nav>

<div class="container">
    {% block body_block %}

    {% endblock %}
</div>
</body>

</html>

templates/list.html
{% extends "blog/index.html" %}


{% block body_block %}


<body>
<div class="container">
     <div class="row">
{% for x, y, z in data %}

    <div class="card border-dark mb-3 column col-sm-6 col-md-5">
       
        <div class="card-text">
            <a href="/blog/view/{{ z }}" class="data-blog awesome"><h4>{{ x|safe|truncatechars:200 }}</h4></a>



        <div class="author">
{{ y }}
        
</div>
    </div>
</div>

{% endfor %}
     </div>
</div>
</body>
<style>
	.author
    {
    font-family: 'Merriweather', serif;
    font-weight: bold;
    font-style: italic;

    }
    .data-blog
    {
font-family: 'Lora', serif;
    }
    .data-blog
    {
    color: black;
    }
.card
{
width:17em;
height: 7em;
margin: 1em;
}
.awesome {
color:#313131;
      -webkit-animation:colorchange 20s infinite alternate;
}
@-webkit-keyframes colorchange {
      0% {

        color: blue;
      }

      10% {

        color: #8e44ad;
      }

      20% {

        color: #1abc9c;
      }

      30% {

        color: #d35400;
      }

      40% {

        color: blue;
      }

      50% {

        color: #34495e;
      }

      60% {

        color: blue;
      }

      70% {

        color: #2980b9;
      }
      80% {

        color: #f1c40f;
      }

      90% {

        color: #2980b9;
      }

      100% {

        color: pink;
      }
    }
    .row
    {
    padding-left:100px;
    }



</style>

{% endblock %}

templates/view.html
{% extends "blog/index.html" %}


{% block body_block %}
<body>
	<div class="container">
		<h1>{{ title|safe}}</h1>

		<p>{{ data|safe }}</p>

<i>{{ author|safe }}</i>
</div>
</body>
{% endblock %}

templates/writting.html
{% extends "blog/index.html" %}


{% block body_block %}
<div class="container">
    <form method="post">
    {% csrf_token %}
    {{ form.as_p}}

    <input type="submit" value="Submit" class="btn btn-primary mb-3">
</form>
</div>
<script>
var editor = new MediumEditor('.editable');
editor.addElements('.editable');


</script>

{% endblock %}